# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\wangyi\Temp_prj\python_prj\csv_handle\gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 522)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_opencsvfile = QtWidgets.QPushButton(Form)
        self.pushButton_opencsvfile.setGeometry(QtCore.QRect(640, 110, 93, 28))
        self.pushButton_opencsvfile.setObjectName("pushButton_opencsvfile")
        self.textEdit_log = QtWidgets.QTextEdit(Form)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 230, 621, 271))
        self.textEdit_log.setObjectName("textEdit_log")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(640, 460, 93, 28))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 621, 211))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 451, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEdit_cfg_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_cfg_path.setObjectName("lineEdit_cfg_path")
        self.horizontalLayout_12.addWidget(self.lineEdit_cfg_path)
        self.pushButton_cfg = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_cfg.setGeometry(QtCore.QRect(480, 20, 93, 28))
        self.pushButton_cfg.setObjectName("pushButton_cfg")
        self.pushButton_plotall = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_plotall.setGeometry(QtCore.QRect(480, 70, 93, 28))
        self.pushButton_plotall.setObjectName("pushButton_plotall")
        self.pushButton_dpc = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_dpc.setGeometry(QtCore.QRect(480, 130, 93, 28))
        self.pushButton_dpc.setObjectName("pushButton_dpc")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 70, 181, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spinBox_del_rows = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_del_rows.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_del_rows.setMinimum(0)
        self.spinBox_del_rows.setMaximum(999)
        self.spinBox_del_rows.setProperty("value", 35)
        self.spinBox_del_rows.setObjectName("spinBox_del_rows")
        self.horizontalLayout_8.addWidget(self.spinBox_del_rows)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 201, 151))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 181, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_plot_tilte_content = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_plot_tilte_content.setObjectName("lineEdit_plot_tilte_content")
        self.horizontalLayout.addWidget(self.lineEdit_plot_tilte_content)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 50, 181, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.spinBox_plot_title_fontsize = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_plot_title_fontsize.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_plot_title_fontsize.setMinimum(1)
        self.spinBox_plot_title_fontsize.setProperty("value", 16)
        self.spinBox_plot_title_fontsize.setObjectName("spinBox_plot_title_fontsize")
        self.horizontalLayout_7.addWidget(self.spinBox_plot_title_fontsize)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 80, 181, 23))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.doubleSpinBox_width = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.doubleSpinBox_width.setDecimals(0)
        self.doubleSpinBox_width.setMinimum(0.0)
        self.doubleSpinBox_width.setMaximum(99999.0)
        self.doubleSpinBox_width.setProperty("value", 640.0)
        self.doubleSpinBox_width.setObjectName("doubleSpinBox_width")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_width)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 110, 181, 23))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.doubleSpinBox_hight = QtWidgets.QDoubleSpinBox(self.layoutWidget_6)
        self.doubleSpinBox_hight.setDecimals(0)
        self.doubleSpinBox_hight.setMinimum(0.0)
        self.doubleSpinBox_hight.setMaximum(99999.0)
        self.doubleSpinBox_hight.setProperty("value", 480.0)
        self.doubleSpinBox_hight.setObjectName("doubleSpinBox_hight")
        self.horizontalLayout_14.addWidget(self.doubleSpinBox_hight)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 20, 161, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 138, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBox_plot_start = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_plot_start.setMinimum(1)
        self.spinBox_plot_start.setMaximum(999)
        self.spinBox_plot_start.setProperty("value", 5)
        self.spinBox_plot_start.setObjectName("spinBox_plot_start")
        self.horizontalLayout_2.addWidget(self.spinBox_plot_start)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 70, 138, 23))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_plot_end = QtWidgets.QSpinBox(self.layoutWidget5)
        self.spinBox_plot_end.setMinimum(1)
        self.spinBox_plot_end.setMaximum(999)
        self.spinBox_plot_end.setProperty("value", 5)
        self.spinBox_plot_end.setObjectName("spinBox_plot_end")
        self.horizontalLayout_3.addWidget(self.spinBox_plot_end)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 20, 211, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 20, 153, 21))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_ylim_noset = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_ylim_noset.setChecked(True)
        self.radioButton_ylim_noset.setObjectName("radioButton_ylim_noset")
        self.horizontalLayout_4.addWidget(self.radioButton_ylim_noset)
        self.radioButton_ylim_set = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioButton_ylim_set.setObjectName("radioButton_ylim_set")
        self.horizontalLayout_4.addWidget(self.radioButton_ylim_set)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(11, 51, 194, 23))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.doubleSpinBox_ylim_min = QtWidgets.QDoubleSpinBox(self.layoutWidget7)
        self.doubleSpinBox_ylim_min.setMinimum(-99999.0)
        self.doubleSpinBox_ylim_min.setMaximum(99999.0)
        self.doubleSpinBox_ylim_min.setObjectName("doubleSpinBox_ylim_min")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_ylim_min)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(11, 81, 194, 23))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.doubleSpinBox_ylim_max = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.doubleSpinBox_ylim_max.setMinimum(-99999.0)
        self.doubleSpinBox_ylim_max.setMaximum(99999.0)
        self.doubleSpinBox_ylim_max.setSingleStep(1.0)
        self.doubleSpinBox_ylim_max.setProperty("value", 5.0)
        self.doubleSpinBox_ylim_max.setObjectName("doubleSpinBox_ylim_max")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_ylim_max)
        self.pushButton_plot = QtWidgets.QPushButton(self.tab)
        self.pushButton_plot.setGeometry(QtCore.QRect(510, 150, 93, 28))
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_splitfile = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_splitfile.setGeometry(QtCore.QRect(500, 120, 93, 28))
        self.pushButton_splitfile.setObjectName("pushButton_splitfile")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 161, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 141, 23))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.spinBox_split_start = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_split_start.setMinimum(1)
        self.spinBox_split_start.setMaximum(999)
        self.spinBox_split_start.setProperty("value", 5)
        self.spinBox_split_start.setObjectName("spinBox_split_start")
        self.horizontalLayout_9.addWidget(self.spinBox_split_start)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 70, 141, 23))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.spinBox_split_end = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_split_end.setMinimum(1)
        self.spinBox_split_end.setMaximum(999)
        self.spinBox_split_end.setProperty("value", 5)
        self.spinBox_split_end.setObjectName("spinBox_split_end")
        self.horizontalLayout_10.addWidget(self.spinBox_split_end)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(220, 50, 221, 23))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lineEdit_split_filename = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_split_filename.setObjectName("lineEdit_split_filename")
        self.horizontalLayout_11.addWidget(self.lineEdit_split_filename)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.layoutWidget9 = QtWidgets.QWidget(Form)
        self.layoutWidget9.setGeometry(QtCore.QRect(650, 40, 83, 47))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_opendat = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radioButton_opendat.setChecked(True)
        self.radioButton_opendat.setObjectName("radioButton_opendat")
        self.verticalLayout.addWidget(self.radioButton_opendat)
        self.radioButton_opencsv = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radioButton_opencsv.setObjectName("radioButton_opencsv")
        self.verticalLayout.addWidget(self.radioButton_opencsv)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_clear.clicked.connect(Form.on_btn_clear_click)
        self.pushButton_opencsvfile.clicked.connect(Form.on_btn_openfile_click)
        self.pushButton_plot.clicked.connect(Form.on_btn_plot_click)
        self.pushButton_splitfile.clicked.connect(Form.on_btn_splitfile_click)
        self.pushButton_dpc.clicked.connect(Form.on_btn_dpc_click)
        self.pushButton_cfg.clicked.connect(Form.on_btn_cfg_click)
        self.pushButton_plotall.clicked.connect(Form.on_btn_plotall_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CSV绘图工具"))
        self.pushButton_opencsvfile.setText(_translate("Form", "打开数据"))
        self.pushButton_clear.setText(_translate("Form", "清空"))
        self.label_11.setText(_translate("Form", "配置文件路径"))
        self.lineEdit_cfg_path.setText(_translate("Form", "config.csv"))
        self.pushButton_cfg.setText(_translate("Form", "导入配置"))
        self.pushButton_plotall.setText(_translate("Form", "批量画图"))
        self.pushButton_dpc.setText(_translate("Form", "DPC画图"))
        self.label_7.setText(_translate("Form", "剔除无效行数："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "自动绘图"))
        self.groupBox.setTitle(_translate("Form", "曲线标题设置"))
        self.label.setText(_translate("Form", "名称："))
        self.lineEdit_plot_tilte_content.setText(_translate("Form", "曲线一"))
        self.label_2.setText(_translate("Form", "曲线标题字号："))
        self.label_12.setText(_translate("Form", "图片宽度："))
        self.label_13.setText(_translate("Form", "图片高度："))
        self.groupBox_2.setTitle(_translate("Form", "数据选择"))
        self.label_3.setText(_translate("Form", "起始序号："))
        self.label_4.setText(_translate("Form", "结束序号："))
        self.groupBox_3.setTitle(_translate("Form", "Y轴范围设置"))
        self.radioButton_ylim_noset.setText(_translate("Form", "默认"))
        self.radioButton_ylim_set.setText(_translate("Form", "手动设置"))
        self.label_5.setText(_translate("Form", "Y轴最小值："))
        self.label_6.setText(_translate("Form", "Y轴最大值："))
        self.pushButton_plot.setText(_translate("Form", "手动画图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "手动绘图"))
        self.pushButton_splitfile.setText(_translate("Form", "拆分文件"))
        self.groupBox_4.setTitle(_translate("Form", "数据选择"))
        self.label_8.setText(_translate("Form", "起始列号："))
        self.label_9.setText(_translate("Form", "结束列号："))
        self.label_10.setText(_translate("Form", "文件名："))
        self.lineEdit_split_filename.setText(_translate("Form", "曲线一.csv"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "文件拆分"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "数据筛选"))
        self.radioButton_opendat.setText(_translate("Form", "DAT文件"))
        self.radioButton_opencsv.setText(_translate("Form", "CSV文件"))

